package constants

const UTF8 = "UTF-8"
const GBK = "GBK"
const WWW = "www."
const HTTP = "http://"
const HTTPS = "https://"
const SUCCESS = "0"
const FAIL = "1"
const LOGIN_SUCCESS = "Success"
const LOGOUT = "Logout"
const REGISTER = "Register"
const LOGIN_FAIL = "Error"
const ALL_PERMISSION = "*:*:*"
const SUPER_ADMIN = "admin"
const ROLE_DELIMETER = ","
const PERMISSION_DELIMETER = ","
const CAPTCHA_EXPIRATION = 2
const TOKEN = "token"
const TOKEN_PREFIX = "Bearer "
const RESOURCE_PREFIX = "/profile"
const LOOKUP_RMI = "rmi:"
const LOOKUP_LDAP = "ldap:"
const LOOKUP_LDAPS = "ldaps:"
